import React from 'react';
import { CopyPromptButton } from '@/components/CopyPromptButton';
import { buildMailtoLinks, type StaticMissionStartDto } from '@/lib/public-invite';

export function MissionStartView({ dto }: { dto: StaticMissionStartDto }) {
  const links = buildMailtoLinks(dto);
  const supportAction = <a className="button" href={links.help}>Contact Darryl</a>;
  const completionHeading = dto.missionSlug === 'get-ready-to-run-certifyd-core' ? "You're ready when..." : "You're done when...";
  return <main className="main"><div className="container"><section className="panel"><p className="eyebrow">{dto.missionEyebrow}</p><h1>{dto.startHeading}</h1><p className="muted lead">{dto.startIntro}</p>{dto.sections.map((section) => <div className="panel" key={section.heading}><p className="eyebrow">{section.heading}</p><p className="muted lead">{section.body}</p></div>)}{dto.choices.length ? <div className="grid grid-2">{dto.choices.map((choice) => <article className="panel" key={choice.label}><h2>{choice.label}</h2><p className="muted">{choice.copy}</p>{choice.href && choice.actionLabel ? <a className="button" href={choice.href} target="_blank" rel="noopener noreferrer">{choice.actionLabel}</a> : null}</article>)}</div> : null}{dto.aiPrompt ? <><div className="panel"><p className="eyebrow">AI coding agent path</p><p className="muted">{dto.publicInstructions}</p><textarea id="ai-prompt" readOnly defaultValue={dto.aiPrompt} /><div className="actions"><CopyPromptButton value={dto.aiPrompt} label="Copy Certifyd Setup Prompt" />{dto.repositoryUrl ? <a className="button" href={dto.repositoryUrl} target="_blank" rel="noopener noreferrer">Open Core Repository</a> : null}</div></div><div className="panel"><p className="eyebrow">Prefer the command line?</p><p className="lead muted">Open the Certifyd Core repository and follow the installation documentation directly.</p><div className="actions">{dto.repositoryUrl ? <a className="button" href={dto.repositoryUrl} target="_blank" rel="noopener noreferrer">Open Core Repository</a> : null}{supportAction}</div><p className="muted">Use Contact Darryl if setup is unclear, your agent cannot continue, or you hit a real blocker.</p></div></> : <div className="panel"><p className="eyebrow">Agent ready?</p><p className="lead">{dto.continuationIntro || dto.publicInstructions}</p><div className="actions">{dto.continuationPath && dto.continuationLabel ? <a className="button primary" href={dto.continuationPath}>{dto.continuationLabel}</a> : null}{supportAction}</div><p className="muted">Use Contact Darryl only if something is unclear, your AI agent will not work, or you need white-glove help.</p></div>}<div className="panel"><p className="eyebrow">{completionHeading}</p><p className="lead">{dto.successCriteria}</p></div><p><a className="button" href={`/invite/${dto.code}/`}>Return to invite</a></p></section></div></main>;
}
