export const dynamic = 'force-dynamic';

import { missionAction, milestoneAction } from '@/lib/actions';
import { prisma } from '@/lib/db';

export default async function MissionsPage() {
  const missions = await prisma.mission.findMany({ include: { milestones: { orderBy: { sortOrder: 'asc' } } }, orderBy: { sequence: 'asc' } });
  return <div className="grid"><section className="panel"><h1>Missions</h1><form className="grid" action={missionAction}><div className="form-grid"><label>Name<input name="name" required /></label><label>Slug<input name="slug" required placeholder="run-your-own-creator-network" /></label><label>Sequence<input name="sequence" type="number" min="0" defaultValue="0" /></label></div><label>Short description<input name="shortDescription" required /></label><label>Invite copy<textarea name="inviteCopy" required defaultValue={"We're opening Certifyd Core to a small number of people during our technical beta. You'll run Certifyd Core in a real creator workflow, use your preferred AI coding agent with the repository and documentation, and work directly with the Certifyd team throughout the beta."} /></label><button className="button primary">Create mission</button></form></section>{missions.map((mission) => <section className="panel" key={mission.id}><p className="eyebrow">{mission.active ? 'Active' : 'Inactive'} · Stage {mission.sequence || '—'}</p><h2>{mission.name}</h2><p className="muted">{mission.shortDescription}</p><ol>{mission.milestones.map((m) => <li key={m.id}>{m.title}<div className="muted">{m.description}</div></li>)}</ol><form className="form-grid" action={milestoneAction}><input type="hidden" name="missionId" value={mission.id} /><label>Milestone title<input name="title" required /></label><label>Description<input name="description" /></label><button className="button">Add milestone</button></form></section>)}</div>;
}
